<?xml version="1.0"?>
<robot name="differential_wheeled_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>


  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

<!-- CONVERSION PROPERTIES -->

<xacro:property name="M_PI" value="3.1415926535897931" />
<xacro:property name="M_PI_2" value="1.570796327" />
<xacro:property name="DEG_TO_RAD" value="0.017453293" />

<!-- ROBOT BODY PROPERTIES -->

<xacro:property name="base_height" value="0.02" /> 
<xacro:property name="base_radius" value="0.15" /> 
<xacro:property name="base_mass" value="5" /> <!-- CHASIS-->

<xacro:property name="caster_f_height" value="0.04" /> 
<xacro:property name="caster_f_radius" value="0.025" /> 
<xacro:property name="caster_f_mass" value="0.5" /> <!-- CASTER WHEEL FRONT-->

<xacro:property name="caster_b_height" value="0.04" /> 
<xacro:property name="caster_b_radius" value="0.025" /> 
<xacro:property name="caster_b_mass" value="0.5" /> <!-- CASTER WHEEL BACK-->

<xacro:property name="base_x_origin_to_wheel_origin" value="0.25" />
<xacro:property name="base_y_origin_to_wheel_origin" value="0.3" /> 
<xacro:property name="base_z_origin_to_wheel_origin" value="0.0" /><!--WHERE TO PLACE WHEELS-->
  
<xacro:property name="wheel_radius" value="0.04" /> 
<xacro:property name="wheel_height" value="0.02" /> <!--height-thickness-->
<xacro:property name="wheel_mass" value="20" /> <!--WHEEL DIMENSIONS-->



<!-- Macro for calculating inertia of cylinder -->
<xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
</xacro:macro>

<!--SENSORS LIDAR HOKUYO-->

<xacro:property name="hokuyo_size" value="0.05" />

<!--STARTING OF DESIGN-->

<!-- base_footprint is a fictitious link(frame) 
that is on the ground right below base_link origin -->

 <link name="base_footprint">
    
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>


<joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin }" rpy="0 0 0"/>
</joint> 



<!--BOT - STARTING DESIGN-->

<link name="base_link">

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
        <material name="White" />
    </visual>

    <inertial>
        <mass value="${base_mass}" />
        <origin xyz="0 0 0" />
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
    </inertial>

    <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
    </collision>
</link>

<gazebo reference="base_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
</gazebo>

<!--caster wheel front-->

<joint name="caster_f_joint" type="fixed">
    <parent link="base_link" />
    <child link="caster_front_link" />
    <origin xyz="0.115 0 0.007" rpy="${-M_PI/2} 0 0" />
</joint>

<link name="caster_front_link" >

    <visual>
        <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <sphere radius="${caster_f_radius}" />
        </geometry>
        <material name="black" />
    </visual>
    
    <inertial>
        <mass value="${caster_f_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" 
                 izz="0.001" />
    </inertial>

    <collision>
        <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <sphere radius="${caster_f_radius}" />
        </geometry>
    </collision>
</link>

<gazebo reference="caster_front_link">
    <turnGravityOff>false</turnGravityOff>
</gazebo>

<!--caster wheel back-->

<joint name="caster_b_joint" type="fixed">
    <parent link="base_link" />
    <child link="caster_back_link" />
    <origin xyz="-0.135 0 0.009" rpy="${-M_PI/2} 0 0" />
</joint>

<link name="caster_back_link" >

    <visual>
        <origin xyz="0.02 0.02 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <sphere radius="${caster_b_radius}" />
        </geometry>
        <material name="black" />
    </visual>
    
    <inertial>
        <mass value="${caster_b_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" 
                 izz="0.001" />
    </inertial>

    <collision>
        <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <sphere radius="${caster_b_radius}" />
        </geometry>
    </collision>
</link>

<gazebo reference="caster_back_link">
    <turnGravityOff>false</turnGravityOff>
</gazebo>

<!--WHEELS OF THE ROBOT-->

<!--right wheel-->

<joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_right_wheel" />
    <origin xyz="0 0.15 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
</joint>

<link name="front_right_wheel" >

    <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
        <material name="Red" />
    </visual>

    <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <xacro:cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />
    </inertial>
    
    <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
    </collision>
</link>

 <gazebo reference="front_right_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

<transmission name="front_right_wheel_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_right_wheel_joint" />
    <actuator name="front_right_wheel_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<!--LEFT WHEEL-->

<joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="front_left_wheel" />
    <origin xyz="0 -0.15 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
</joint>

<link name="front_left_wheel" >

    <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
        <material name="Red" />
    </visual>

    <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <xacro:cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />
    </inertial>

        
    
    <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
    </collision>
</link>

 <gazebo reference="front_left_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

<transmission name="front_left_wheel_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_left_wheel_joint" />
    <actuator name="front_left_wheel_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>

<!--sensors  lidar-->

<joint name="hokuyo_joint" type="fixed">
    <parent link="base_link" />
    <child link="hokuyo_link" />
    <origin xyz="${base_radius - hokuyo_size/2} 0 
                 ${base_height+hokuyo_size/4}" />
</joint>

<link name="hokuyo_link" >
    
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
        </geometry>
      <material name="Blue" />
    </visual>

</link>

<!--wheel plugins and sensor plugins-->

<gazebo reference="hokuyo_link">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose>${hokuyo_size/2} 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin>
    </sensor>
</gazebo>

 
  <!-- Differential drive controller  -->
<gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>front_right_wheel_joint</leftJoint>
      <rightJoint>front_left_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <odometrySource>1</odometrySource>
      <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      
    </plugin>
</gazebo> 

</robot>
